apiVersion: v1
kind: Namespace
metadata:
  name: zxczczx-staging
  labels:
    environmentId: env_5c53d3e6-c9eb-4802-88fb-e4005d4166b4
    projectId: project_27b9f423-1814-4506-96f4-caad344a7cf2
    projectName: zxczczx
    environmentName: staging
    organizationId: org_12ab5a69-48a2-42d7-ad36-d59a2bca4805
