apiVersion: v1
kind: Namespace
metadata:
  name: reddit-dev
  labels:
    environment-id: env_77957abb-1aac-437a-a837-50fc3a606500
    project-id: project_f43e1d57-bf06-4f80-bb30-c6f304040e22
    project-name: reddit
    environment-name: dev
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
