apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  labels:
    app: webapi
    application-id: app_b2bba01f-56de-43e1-93ec-bb6b15765d88
spec:
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
